version: "3"
services: 
    server:
        hostname: server
        build: 
            context: ./server
            dockerfile: Dockerfile.prod
        ports: 
            - 8443:8443
        container_name: poll_server
        restart: always
        depends_on: 
            - database
        environment:
            TZ: "Africa/Nairobi"
        
        networks: 
            - polls_network
    client:
        hostname: client
        build: 
            context: ./client
            dockerfile: Dockerfile
        ports: 
            - 80:80
            - 443:443

        depends_on: 
            - server
        environment:
            TZ: "Africa/Nairobi"

        container_name: poll_client
        
        networks: 
            - polls_network
    redis:
        hostname: redis
        image: redis:alpine
        hostname: redis
        restart: always
        volumes:
            - ../data/redis:/data
        entrypoint: redis-server --appendonly yes
        ports:
            - 6379:6379
        environment:
            TZ: "Africa/Nairobi"

        networks:
            - polls_network
    database:
        hostname: database
        image: postgres:alpine
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: polls-db-prod
            TZ: "Africa/Nairobi"
            
        healthcheck:
            test: ['CMD-SHELL', 'pg_is ready -U postgres']
            interval: 10s
            timeout: 5s
            retries: 5
        restart: always
        depends_on: 
            - redis
        volumes: 
            - ../data/pg-data:/var/libs/postgresql/data
        ports: 
            - 5432:5432
        networks:
            - polls_network
networks:
    polls_network:
         driver: bridge


